[pytest]
addopts = --headed --slowmo 500 --screenshot only-on-failure --video retain-on-failure --html=report.html --self-contained-html

python_files = [0-11]*_test_*.py test_*.py *_test.py
python_functions = test_*
python_classes = Test*